# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true # PR 에서만 오토 라벨링 허용
# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.
# 레이블
labels:
  '✨ Feature':
    include:
      - '\bFeature\b'    # 일반적인 신규 기능 추가 pr title
  '🐧 Feature':
    include:
      - '\bExperiment\b' # 퍼펭팀의 신규 기능 추가 pr title
  '💡 Improvement':
    include:
      - '\bStyle\b'      # 코드 스타일 변경 pr title
      - '\bDesign\b'     # CSS 등 UI 디자인 변경 pr title
      - '\bRefector\b'   # 코드 리팩토링 pr title
      - '\bImprove\b'    # 기능, 구조, 성능 등의 개선 pr title
      - '\bImplement\b'  # 새로운 것들이 구현된 경우 pr title
  '🐞 BugFix':
    include:
      - '\bFix\b'        # 버그 수정 및 결함 처리 pr title
  '🚑 Hotfix':
    include:
      - '\bHotfix\b'     # 긴급 수정 사항 pr title
  '🔀 Merge':
    include:
      - '\bMerge\b'      # 단순 병합 시, 릴리즈 노트에서 제외할 용도로 사용하는 pr title
  '🔖 Release:patch':
    include:
      - '\bRelease:patch\b' # 메이저 버전 업데이트 시 사용될 레이블, pr title
  '🔖 Release:minor':
    include:
      - '\bRelease:minor\b' # 마이너 버전 업데이트 시 사용될 레이블, pr title
  '🔖 Release:major':
    include:
      - '\bRelease:major\b' # 패치 버전 업데이트 시 사용될 레이블, pr title