name: QShop Editor Deploy

on:
  push:
    branches:
      - prod
      - stg
      - dev

jobs:
  # deploy
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'