name: QShop Editor Deploy Release Drafter

on:
  pull_request:
    types: [closed]

jobs:
  # release drafter
  update_release_draft:
    if: github.event.pull_request.merged == true && github.base_ref == 'prod'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
            config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}